# Generated by Django 3.2.15 on 2023-01-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221103_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingredient',
            new_name='Ingredients',
        ),
    ]
